# Generated by Django 5.1.4 on 2024-12-22 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_proctor_test_instructor_course_testassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='courses',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
