# Generated by Django 5.1.4 on 2024-12-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_test_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='courses',
            new_name='course',
        ),
    ]
