# Generated by Django 5.1.4 on 2024-12-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_question_user_answer_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
